name: Feature request
description: Suggest an idea
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What would you like to see?
    validations:
      required: true
